inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*

Documentation:
  Enabled: false

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

NumericLiterals:
  Enabled: false
