AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*

Documentation:
  Enabled: false

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Max: 120

NumericLiterals:
  Enabled: false
