default: &default
  service_name: santa
  secret_token: <%= ENV['SECRET_TOKEN'] || 'replace-me' %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || 'replace-me' %>
  base_url: <%= ENV['BASE_URL'] || 'http://localhost:9292' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
